/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterLineRepairRouteImport } from './routes/water-line-repair'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResidentialPlumbingRouteImport } from './routes/residential-plumbing'
import { Route as PlumbingSystemReplacementRouteImport } from './routes/plumbing-system-replacement'
import { Route as PlumbingInspectionsRouteImport } from './routes/plumbing-inspections'
import { Route as LeakDetectionRouteImport } from './routes/leak-detection'
import { Route as HotWaterRecirculationPumpsRouteImport } from './routes/hot-water-recirculation-pumps'
import { Route as FaucetRepairRouteImport } from './routes/faucet-repair'
import { Route as EmergencyPlumbingRouteImport } from './routes/emergency-plumbing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialPlumbingRouteImport } from './routes/commercial-plumbing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas.$slug'

const WaterLineRepairRoute = WaterLineRepairRouteImport.update({
  id: '/water-line-repair',
  path: '/water-line-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialPlumbingRoute = ResidentialPlumbingRouteImport.update({
  id: '/residential-plumbing',
  path: '/residential-plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingSystemReplacementRoute =
  PlumbingSystemReplacementRouteImport.update({
    id: '/plumbing-system-replacement',
    path: '/plumbing-system-replacement',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlumbingInspectionsRoute = PlumbingInspectionsRouteImport.update({
  id: '/plumbing-inspections',
  path: '/plumbing-inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const LeakDetectionRoute = LeakDetectionRouteImport.update({
  id: '/leak-detection',
  path: '/leak-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const HotWaterRecirculationPumpsRoute =
  HotWaterRecirculationPumpsRouteImport.update({
    id: '/hot-water-recirculation-pumps',
    path: '/hot-water-recirculation-pumps',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaucetRepairRoute = FaucetRepairRouteImport.update({
  id: '/faucet-repair',
  path: '/faucet-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyPlumbingRoute = EmergencyPlumbingRouteImport.update({
  id: '/emergency-plumbing',
  path: '/emergency-plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialPlumbingRoute = CommercialPlumbingRouteImport.update({
  id: '/commercial-plumbing',
  path: '/commercial-plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiceAreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-plumbing': typeof CommercialPlumbingRoute
  '/contact': typeof ContactRoute
  '/emergency-plumbing': typeof EmergencyPlumbingRoute
  '/faucet-repair': typeof FaucetRepairRoute
  '/hot-water-recirculation-pumps': typeof HotWaterRecirculationPumpsRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/plumbing-inspections': typeof PlumbingInspectionsRoute
  '/plumbing-system-replacement': typeof PlumbingSystemReplacementRoute
  '/residential-plumbing': typeof ResidentialPlumbingRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/water-line-repair': typeof WaterLineRepairRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-plumbing': typeof CommercialPlumbingRoute
  '/contact': typeof ContactRoute
  '/emergency-plumbing': typeof EmergencyPlumbingRoute
  '/faucet-repair': typeof FaucetRepairRoute
  '/hot-water-recirculation-pumps': typeof HotWaterRecirculationPumpsRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/plumbing-inspections': typeof PlumbingInspectionsRoute
  '/plumbing-system-replacement': typeof PlumbingSystemReplacementRoute
  '/residential-plumbing': typeof ResidentialPlumbingRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/water-line-repair': typeof WaterLineRepairRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-plumbing': typeof CommercialPlumbingRoute
  '/contact': typeof ContactRoute
  '/emergency-plumbing': typeof EmergencyPlumbingRoute
  '/faucet-repair': typeof FaucetRepairRoute
  '/hot-water-recirculation-pumps': typeof HotWaterRecirculationPumpsRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/plumbing-inspections': typeof PlumbingInspectionsRoute
  '/plumbing-system-replacement': typeof PlumbingSystemReplacementRoute
  '/residential-plumbing': typeof ResidentialPlumbingRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/water-line-repair': typeof WaterLineRepairRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial-plumbing'
    | '/contact'
    | '/emergency-plumbing'
    | '/faucet-repair'
    | '/hot-water-recirculation-pumps'
    | '/leak-detection'
    | '/plumbing-inspections'
    | '/plumbing-system-replacement'
    | '/residential-plumbing'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/water-line-repair'
    | '/service-areas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial-plumbing'
    | '/contact'
    | '/emergency-plumbing'
    | '/faucet-repair'
    | '/hot-water-recirculation-pumps'
    | '/leak-detection'
    | '/plumbing-inspections'
    | '/plumbing-system-replacement'
    | '/residential-plumbing'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/water-line-repair'
    | '/service-areas/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial-plumbing'
    | '/contact'
    | '/emergency-plumbing'
    | '/faucet-repair'
    | '/hot-water-recirculation-pumps'
    | '/leak-detection'
    | '/plumbing-inspections'
    | '/plumbing-system-replacement'
    | '/residential-plumbing'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/water-line-repair'
    | '/service-areas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialPlumbingRoute: typeof CommercialPlumbingRoute
  ContactRoute: typeof ContactRoute
  EmergencyPlumbingRoute: typeof EmergencyPlumbingRoute
  FaucetRepairRoute: typeof FaucetRepairRoute
  HotWaterRecirculationPumpsRoute: typeof HotWaterRecirculationPumpsRoute
  LeakDetectionRoute: typeof LeakDetectionRoute
  PlumbingInspectionsRoute: typeof PlumbingInspectionsRoute
  PlumbingSystemReplacementRoute: typeof PlumbingSystemReplacementRoute
  ResidentialPlumbingRoute: typeof ResidentialPlumbingRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WaterLineRepairRoute: typeof WaterLineRepairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-line-repair': {
      id: '/water-line-repair'
      path: '/water-line-repair'
      fullPath: '/water-line-repair'
      preLoaderRoute: typeof WaterLineRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential-plumbing': {
      id: '/residential-plumbing'
      path: '/residential-plumbing'
      fullPath: '/residential-plumbing'
      preLoaderRoute: typeof ResidentialPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-system-replacement': {
      id: '/plumbing-system-replacement'
      path: '/plumbing-system-replacement'
      fullPath: '/plumbing-system-replacement'
      preLoaderRoute: typeof PlumbingSystemReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-inspections': {
      id: '/plumbing-inspections'
      path: '/plumbing-inspections'
      fullPath: '/plumbing-inspections'
      preLoaderRoute: typeof PlumbingInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leak-detection': {
      id: '/leak-detection'
      path: '/leak-detection'
      fullPath: '/leak-detection'
      preLoaderRoute: typeof LeakDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-water-recirculation-pumps': {
      id: '/hot-water-recirculation-pumps'
      path: '/hot-water-recirculation-pumps'
      fullPath: '/hot-water-recirculation-pumps'
      preLoaderRoute: typeof HotWaterRecirculationPumpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet-repair': {
      id: '/faucet-repair'
      path: '/faucet-repair'
      fullPath: '/faucet-repair'
      preLoaderRoute: typeof FaucetRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-plumbing': {
      id: '/emergency-plumbing'
      path: '/emergency-plumbing'
      fullPath: '/emergency-plumbing'
      preLoaderRoute: typeof EmergencyPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-plumbing': {
      id: '/commercial-plumbing'
      path: '/commercial-plumbing'
      fullPath: '/commercial-plumbing'
      preLoaderRoute: typeof CommercialPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
  }
}

interface ServiceAreasRouteChildren {
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialPlumbingRoute: CommercialPlumbingRoute,
  ContactRoute: ContactRoute,
  EmergencyPlumbingRoute: EmergencyPlumbingRoute,
  FaucetRepairRoute: FaucetRepairRoute,
  HotWaterRecirculationPumpsRoute: HotWaterRecirculationPumpsRoute,
  LeakDetectionRoute: LeakDetectionRoute,
  PlumbingInspectionsRoute: PlumbingInspectionsRoute,
  PlumbingSystemReplacementRoute: PlumbingSystemReplacementRoute,
  ResidentialPlumbingRoute: ResidentialPlumbingRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WaterLineRepairRoute: WaterLineRepairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
